<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalOtomation" Class="HospitalDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-HGV1LOO;Initial Catalog=HospitalOtomation;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HospitalOtomationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="dp_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dp_Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dp_Aciklama" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Association Name="Department_Doctor" Member="Doctors" ThisKey="dp_ID" OtherKey="dp_ID" Type="Doctor" />
    </Type>
  </Table>
  <Table Name="dbo.Doctors" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="dt_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dt_TC" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="dt_Password" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="dt_NameSurname" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="dt_Adres" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="dt_Tel" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="dt_Cinsiyet" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="dt_Dog_Tarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dt_Baslangic_Tarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dt_ResimUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="dp_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Doctor_PastExamine" Member="PastExamines" ThisKey="dt_ID" OtherKey="dt_ID" Type="PastExamine" />
      <Association Name="Department_Doctor" Member="Department" ThisKey="dp_ID" OtherKey="dp_ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PastExamine" Member="PastExamines">
    <Type Name="PastExamine">
      <Column Name="ex_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ex_Aciklama" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ex_Sonuc" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ex_Tarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ex_Ucret" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="pt_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dt_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Doctor_PastExamine" Member="Doctor" ThisKey="dt_ID" OtherKey="dt_ID" Type="Doctor" IsForeignKey="true" />
      <Association Name="Patient_PastExamine" Member="Patient" ThisKey="pt_ID" OtherKey="pt_ID" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patients" Member="Patients">
    <Type Name="Patient">
      <Column Name="pt_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pt_TC" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="pt_Password" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="pt_NameSurname" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pt_Adres" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="pt_Tel" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="pt_Cinsiyet" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="pt_Dog_Tarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="pt_AnneAdi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pt_BabaAdi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pt_KanGrubu" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="pt_Meslek" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="pt_SigortaTuru" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="pt_ResimUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Patient_PastExamine" Member="PastExamines" ThisKey="pt_ID" OtherKey="pt_ID" Type="PastExamine" />
    </Type>
  </Table>
</Database>